# CONFIGURATION FILE FOR cycle_optimizer.py - power_curves.py 
# Reported values correspond to the current state of kitepower system June 2025

# Kite mass, area, and aerodynamic properties
kite:
  mass: 60                      # kg
  projected_area: 46.86         # m2
  drag_coefficient:
    powered: 0.14
    depowered: 0.08
  lift_coefficient:
    powered: 0.78
    depowered: 0.33

# Tether properties
tether:
  length: 400                   # m
  diameter: 0.014               # m
  density: 617.1314119889819    # kg/m3
  drag_coefficient: 1.1         # -

# Bounds to the optimisation
bounds:
  avg_elevation: # Average elevation angle during reel out
    min: 30.                    # deg
    max: 60.                    # deg
  max_azimuth:  # Maximum azimuth angle during reel out (max flight cone width)
    min: 30.                    # deg
    max: 45.                    # deg
  relative_elevation: # Maximum elevation relative to the average elevation (max flight cone height)
    min: 8                      # deg
    max: 12                      # deg 
  force_limits: # Minimum force to have control on the kite 
    min: 300                    # kgf
    max: 2750                   # kgf
  speed_limits: # Should be both positive, so the full range is [-max, -min] U [min, max]
    min: 0.0                    # m/s
    max: 10.5                   # m/s
  tether_stroke:
    min: 50                     # m
    max: 150                    # m
  minimum_tether_length: # Tether length at start of reel-out
    min: 160                    # m
    max: 300                    # m
  
  
